### ISSUE TITLE
parity on kovan testnet stalling when in daemon mode

### ISSUE THREAD

**Issue by brenzi** [kovan-testnet/config#5]
*  Parity/v1.6.0-unstable-d3ee15c-20170131/x86_64-linux-gnu/rustc1.14.0

My parity client often stalls and loses connections (0/0/25) when I run it in daemon mode

```
 /usr/bin/parity daemon /tmp/parity.pid --chain=/home/ethadm/.local/share/io.parity.ethereum/kovan.json 
```

This doesn't happen if I call it without "daemon" argument

Ideas?

**Comment by IstoraMandiri** [comment]
Hi, you shouldn't be using the JSON file anymore. Just start with `--chain=kovan`
